### ISSUE TITLE
Provide a proper readme with setup instructions

### ISSUE THREAD

**Issue by sebastian-r** [tnunamak/tech-radar#4]
Hi,

would be nice to have a the ReadMe contain instructions on how to use your project...

best
Sebastian

**Comment by tnunamak** [comment]
Hi Sebastian, you are right! This project has been mostly untouched for a few years and I have been meaning to rewrite it, but I can't promise anything any time soon. In the meantime,

* npm install
* bower install
* grunt server

Should get it up and running... although there is a good chance the dependencies are so out of date they won't come down properly.

**Comment by sebastian-r** [comment]
hi, thx a lot :D

**Comment by eric1dat** [comment]
Hello,

this project is a cool a concept and fits in perfectly for displaying technologies as they relate to my organization.   I've installed the elements you mentioned in your Jan 30 post; given that, what file launches the app?


cheers

**Comment by eric1dat** [comment]
Never mind my previous, I was able to build and run the project.  Great job and thanks.


Cheers

**Comment by tnunamak** [comment]
@eric1dat thanks! You guys have me thinking about working on this again soon!

**Comment by evkostadinov** [comment]
Hi @tnunamak,

Great job putting all this together, but a liitle more descriptive <code>Readme</code> will really be helpful. Can you find some time and add such? It's a nightmare for non front-ender to make it work.

Thanks.

**Comment by tnunamak** [comment]
I've added a note to the [README](https://github.com/tnunamak/tech-radar#installing) that will hopefully help establish a starting point for anyone looking to make use of this project, although please proceed at your own risk.

Thanks for feedback and interest.
